version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: experiment-db
      POSTGRES_USER: experiment-user
      POSTGRES_PASSWORD: experiment-password
    ports:
      - "5432:5432"
    volumes:
      - ./db_misc/postgres_data:/var/lib/postgresql/data


